version: "3"
services:
  php-webshop:
    build:
      context: .
      dockerfile: ./Dockerfile
    ports:
      - "80:80"
    volumes:
      - ./app:/var/www/html
    working_dir:
      /var/www/html
    command:
      bash -c "apachectl start && composer install && sleep infinity"
